---

- name: Install ZSH with Aptitude
  apt: pkg=zsh state=latest update_cache=yes cache_valid_time={{ aptcachetime }}

- name: Make ZSH default shell for user root
  user: name=root shell=/bin/zsh

- name: Copy default ZSH config for user root
  copy: src="zshrc" dest="/root/.zshrc" owner="root" group="root" force=yes

- name: "Make ZSH default shell for user {{ ansible_env.USER }}"
  user: name={{ ansible_env.USER }} shell=/bin/zsh

- name: "Copy default ZSH config for user {{ ansible_env.USER }}"
  copy: src="zshrc" dest="{{ ansible_env.HOME }}/.zshrc" owner="{{ ansible_env.USER }}" group="{{ ansible_env.USER }}" force=yes

- git: 
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"

- git: 
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: "{{ ansible_env.HOME }}/.zsh/zsh-autosuggestions"

- name: "Install fzf finder"
  apt: 
    name: fzf 
# Example git checkout from Ansible Playbooks
#- git:
#    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
#    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
