- name: Install tmux package
  apt:
    name: tmux
    state: present
    update_cache: yes

- name: Copy .tmux
  unarchive:
    src: .tmux.tar.gz
    dest: "{{ ansible_env.HOME  }}"

- name: Install tmux conf
  shell: |
    sudo ln -s -f {{ansible_env.HOME}}/.tmux/.tmux.conf
    sudo cp {{ansible_env.HOME}}/.tmux/.tmux.conf.local {{ansible_env.HOME}}
  become: yes
  become_user: "{{ansible_env.USER }}"

- name: Create a symbolic link
  file:
    src: "{{ ansible_env.HOME }}/.tmux/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
