
- name: Remove "vim-tiny" package
  apt:
    name: vim-tiny
    state: absent
    update_cache: yes

- name: Add "vim" repository 
  apt_repository:
    repo: ppa:jonathonf/vim

- name: Install full-vim package
  apt:
    name: vim
    state: present
    update_cache: yes

# This configuration comes from https://github.com/amix/vimrc    
# - name: copy consul_ui files
#   command: cp -r .vim_runtime {{ansible_env.HOME}}

- name: Copy .vim_runtime
  unarchive:
    src: .vim_runtime.tar.gz
    dest: "{{ ansible_env.HOME  }}"

- name: Copy .vimrc
  copy:
    src: .vimrc
    dest: "{{ ansible_env.HOME  }}"
    owner: "{{ ansible_env.USER  }}"
    group: "{{ ansible_env.USER  }}"
